
server:
  port: 9090
spring:
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive
    
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user_service/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallBack
        - id: CONTACT-SERVICE
          uri: lb://CONTACT-SERVICE
          predicates:
            - Path=/contact_service/**
          filters:
            - name: CircuitBreaker
              args:
                name: CONTACT-SERVICE
                fallbackuri: forward:/contactServiceFallBack  
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMileseconds: 4000                

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        

  
