
server:
  port: 8082
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/contact_service
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: CONTACT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/